workflows:
  my-workflow:
    name: My workflow name
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      groups:
        - cicd
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: 13.4
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Create file GoogleService-Info.plist
        script: |
          cd ios; cat << EOF >> GoogleService-Info.plist
          $GOOGLE_SERVICE_IOS
          EOF
      - name: Create file app_store_connect_key.p8
        script: |
          cd ios; cat << EOF >> app_store_connect_key.p8
          $APP_STORE_CONNECT_AUTH_KEY_P8
          EOF
      - name: Create file distribute_p12_base64.txt
        script: |
          cd ios; cat << EOF >> distribute_p12_base64.txt
          $DISTRIBUTION_P12_BASE64
          EOF
      - name : Generate distribution.p12
        script : base64 -d ios/distribute_p12_base64.txt > ios/distribution.p12
      - name: Create file development_p12_base64.txt
        script: |
          cd ios; cat << EOF >> development_p12_base64.txt
          $DEVELOPMENT_P12_BASE64
          EOF
      - name: Generate development.p12
        script : base64 -d ios/distribute_p12_base64.txt > ios/development.p12
      - name: Create file distribute_profile_base64.txt
        script: |
          cd ios; cat << EOF >> distribute_profile_base64.txt
          $DISTRIBUTE_PROFILE_BASE64
          EOF
      - name : Generate Distribute_comhugemanflutterstarterkit.mobileprovision
        script : base64 -d ios/distribute_profile_base64.txt > ios/Distribute_comhugemanflutterstarterkit.mobileprovision
      - name: Create file adhoc_profile_base64.txt
        script: |
          cd ios; cat << EOF >> adhoc_profile_base64.txt
          $ADHOC_PROFILE_BASE64
          EOF
      - name : AdHoc_comhugemanflutterstarterkit.mobileprovision
        script: base64 -d ios/adhoc_profile_base64.txt > ios/AdHoc_comhugemanflutterstarterkit.mobileprovision
      - name: Install dependencies
        script: make prject/install/package/codemagic
      - name : Pod install
        script: cd ios; pod install
      - name : Generate l10n
        script: make l10n/generate
      - name: Generate mock file for test
        script: make test/generate/mock-file
      - name : fastlane setup
        script : |
          echo hello
          cd ios
          fastlane setup
      - name : fastlane test lab
        script : |
          cd ios
          fastlane test_lab
          
