workflows:
  my-workflow:
    name: My workflow name
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name : flutter build ios
        script: cd ios
      - name : fast lane
        script: fastlane setup
#      - name : flutter build ios --release
#        script: flutter build ios integration_test/main_integration_test.dart --release
#      - name : xcode build
#        script: xcodebuild -workspace ../Runner.xcworkspace -scheme Runner -config Flutter/Release.xcconfig -derivedDataPath build/ios_integ -sdk iphoneos build-for-testing
#      - name : zip file
#        script: cd build/ios_integ/Build/Products/; zip -r ../../../../../ios_tests.zip .

