workflows:
  my-workflow:
    name: My workflow name
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: 11.5
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      cancel_previous_builds: true
    scripts:
      - xcodebuild -showsdks
      - echo 'hello'
